version: '3'

services:
  mysqldb:
    container_name: mysql-logon
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=logon
